spring:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/toDoList-api
    username: compose-postgres
    password: compose-postgres

rabbit:
  queue: EMAIL_SENDING_TASKS
  exchange: exchange
  routing-key: TaskTrackerKey